// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20221208155712_added seed data for regions, walks and walk difficulties.")]
    partial class addedseeddataforregionswalksandwalkdifficulties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5573d920-00f8-4723-b69b-1940d9a7b926"),
                            Area = 13789.0,
                            Code = "NRTHL",
                            Lat = -35.370830400000003,
                            Long = 172.57178250000001,
                            Name = "Northland Region",
                            Population = 194600L
                        },
                        new
                        {
                            Id = new Guid("8f0fa5b3-7892-4aa1-8940-52b45e17e868"),
                            Area = 4894.0,
                            Code = "AUCK",
                            Lat = -36.525320700000002,
                            Long = 173.77857040000001,
                            Name = "Auckland Region",
                            Population = 1718982L
                        },
                        new
                        {
                            Id = new Guid("b9034866-b467-4663-9cb5-b49bc1121513"),
                            Area = 8970.0,
                            Code = "WAIK",
                            Lat = -37.514458400000002,
                            Long = 174.54051279999999,
                            Name = "Waikato Region",
                            Population = 496700L
                        },
                        new
                        {
                            Id = new Guid("b5083949-5c56-47a6-8e14-d50e9a1d1449"),
                            Area = 12230.0,
                            Code = "BAYP",
                            Lat = -37.532825899999999,
                            Long = 175.7642701,
                            Name = "Bay of Plenty Region",
                            Population = 345400L
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("239a4ee9-6d0b-4549-9427-4c7a1381a424"),
                            Name = "writer"
                        },
                        new
                        {
                            Id = new Guid("7b0a60a6-f14e-4b2c-b50f-76e7c8bdb0b1"),
                            Name = "reader"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22881732-88b5-4653-9fbf-ad60f1c55360"),
                            EmailAddress = "joe@doe.com",
                            FirstName = "Joe",
                            LastName = "Doe",
                            Password = "sdFD78s.s#*Flfs-ww",
                            Username = "joedoe"
                        },
                        new
                        {
                            Id = new Guid("9a7b4530-7a8b-4c65-aa22-ef902bd2a928"),
                            EmailAddress = "joeline@doelina.com",
                            FirstName = "Joelina",
                            LastName = "Doeina",
                            Password = "sdFD78s.s#*Flfs-ww",
                            Username = "joelinadoelina"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.User_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bca6750-40b6-45af-a3d6-ad430f9ef558"),
                            RoleId = new Guid("7b0a60a6-f14e-4b2c-b50f-76e7c8bdb0b1"),
                            UserId = new Guid("22881732-88b5-4653-9fbf-ad60f1c55360")
                        },
                        new
                        {
                            Id = new Guid("0f42ed23-2796-4687-b91c-b67ed2deadad"),
                            RoleId = new Guid("239a4ee9-6d0b-4549-9427-4c7a1381a424"),
                            UserId = new Guid("9a7b4530-7a8b-4c65-aa22-ef902bd2a928")
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalkDifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WalkDifficultyId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11803224-9dec-47b8-ac88-1dcae1b286b3"),
                            Length = 1.5,
                            Name = "Waiotemarama Loop Track",
                            RegionId = new Guid("5573d920-00f8-4723-b69b-1940d9a7b926"),
                            WalkDifficultyId = new Guid("5cdc193b-b319-4bb5-967d-408582cfd73c")
                        },
                        new
                        {
                            Id = new Guid("c601a364-6330-4e00-a180-c121a0e052d0"),
                            Length = 2.0,
                            Name = "Mt Eden Volcano Walk",
                            RegionId = new Guid("8f0fa5b3-7892-4aa1-8940-52b45e17e868"),
                            WalkDifficultyId = new Guid("94e7794f-00a9-4071-a0ee-034dd6e217eb")
                        },
                        new
                        {
                            Id = new Guid("8eee7a75-6525-4cea-b943-917b90fb592f"),
                            Length = 3.5,
                            Name = "One Tree Hill Walk",
                            RegionId = new Guid("8f0fa5b3-7892-4aa1-8940-52b45e17e868"),
                            WalkDifficultyId = new Guid("94e7794f-00a9-4071-a0ee-034dd6e217eb")
                        },
                        new
                        {
                            Id = new Guid("02bb8ca3-d9cd-4f12-9c2d-64b5a8f2b56c"),
                            Length = 1.2,
                            Name = "Lonely Bay",
                            RegionId = new Guid("b9034866-b467-4663-9cb5-b49bc1121513"),
                            WalkDifficultyId = new Guid("94e7794f-00a9-4071-a0ee-034dd6e217eb")
                        },
                        new
                        {
                            Id = new Guid("1e4f2b92-b698-4429-b78b-20e96086dd93"),
                            Length = 32.0,
                            Name = "Mt Te Aroha To Wharawhara Track Walk",
                            RegionId = new Guid("b5083949-5c56-47a6-8e14-d50e9a1d1449"),
                            WalkDifficultyId = new Guid("140f9559-7359-430b-90b2-b3881c1c924a")
                        },
                        new
                        {
                            Id = new Guid("9d3264f1-3d42-4afe-a521-724d0ae495cf"),
                            Length = 3.5,
                            Name = "Rainbow Mountain Reserve Walk",
                            RegionId = new Guid("b5083949-5c56-47a6-8e14-d50e9a1d1449"),
                            WalkDifficultyId = new Guid("140f9559-7359-430b-90b2-b3881c1c924a")
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.WalkDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WalksDifficulty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94e7794f-00a9-4071-a0ee-034dd6e217eb"),
                            Code = "Easy"
                        },
                        new
                        {
                            Id = new Guid("5cdc193b-b319-4bb5-967d-408582cfd73c"),
                            Code = "Medium"
                        },
                        new
                        {
                            Id = new Guid("140f9559-7359-430b-90b2-b3881c1c924a"),
                            Code = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.User_Role", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.WalkDifficulty", "WalkDifficulty")
                        .WithMany()
                        .HasForeignKey("WalkDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("WalkDifficulty");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
